const express = require('express')
const cors = require('cors')
const { collectDefaultMetrics, register, Counter } = require('prom-client')

const app = express()
const PORT = process.env.AI_PORT || 8000

// Prometheus metrics
const frameAnalysisTotal = new Counter({
  name: 'ai_frame_analysis_total',
  help: 'Total frames analyzed by AI service',
  labelNames: ['result'],
  registers: [register]
})

const cheatingAlertsTotal = new Counter({
  name: 'ai_cheating_alerts_total',
  help: 'Total cheating alerts generated by AI',
  labelNames: ['alert_type'],
  registers: [register]
})

// Middleware
app.use(cors({
  origin: [
    'http://localhost:4005',
    'http://localhost:3005',
    process.env.BACKEND_URL || 'http://backend:4005',
    process.env.FRONTEND_URL || 'http://frontend:3005'
  ],
  credentials: true
}))

app.use(express.json({ limit: '10mb' }))

// Request logging
app.use((req, res, next) => {
  console.log(`[${new Date().toISOString()}] ${req.method} ${req.path}`)
  next()
})

// Health check
app.get('/health', (req, res) => {
  res.json({ 
    status: 'ok', 
    service: 'ai-proctoring',
    timestamp: new Date().toISOString(),
    port: PORT 
  })
})

// Metrics endpoint
app.get('/metrics', async (req, res) => {
  try {
    res.set('Content-Type', register.contentType)
    res.end(await register.metrics())
  } catch (error) {
    res.status(500).end(error.message)
  }
})

// AI Frame Analysis endpoint
app.post('/analyze-frame', async (req, res) => {
  console.log(`[${new Date().toISOString()}] POST /analyze-frame`)
  
  try {
    const { frame, timestamp, sessionId, userId, examId } = req.body
    
    if (!frame || !sessionId) {
      return res.status(400).json({
        success: false,
        message: 'Frame and sessionId are required'
      })
    }

    // Simulate AI analysis (in production, this would call actual AI/ML models)
    const analysisResult = await analyzeFrame(frame, timestamp)
    
    // Record metrics
    frameAnalysisTotal.labels(analysisResult.violation ? 'violation' : 'clean').inc()
    
    if (analysisResult.violation) {
      cheatingAlertsTotal.labels(analysisResult.violationType).inc()
    }

    console.log(`Frame analysis completed: ${analysisResult.violation ? 'VIOLATION' : 'CLEAN'} - ${analysisResult.violationType || 'none'}`)

    res.json({
      success: true,
      analysis: analysisResult,
      sessionId,
      timestamp: new Date().toISOString()
    })

  } catch (error) {
    console.error('Frame analysis error:', error)
    res.status(500).json({
      success: false,
      message: 'Internal server error'
    })
  }
})

// Cheating Alert endpoint
app.post('/cheating-alert', async (req, res) => {
  console.log(`[${new Date().toISOString()}] POST /cheating-alert`)
  
  try {
    const { userId, examId, alertType, sessionId, evidence } = req.body
    
    if (!userId || !examId || !alertType) {
      return res.status(400).json({
        success: false,
        message: 'userId, examId, and alertType are required'
      })
    }

    // Record the alert
    cheatingAlertsTotal.labels(alertType).inc()
    
    console.log(`Cheating alert recorded: ${alertType} for user ${userId} in exam ${examId}`)

    res.json({
      success: true,
      alert: {
        id: `alert_${Date.now()}`,
        userId,
        examId,
        alertType,
        sessionId,
        evidence,
        timestamp: new Date().toISOString()
      }
    })

  } catch (error) {
    console.error('Cheating alert error:', error)
    res.status(500).json({
      success: false,
      message: 'Internal server error'
    })
  }
})

// Simulated AI analysis function
async function analyzeFrame(frame, timestamp) {
  // In production, this would use actual computer vision models
  // For now, we'll simulate basic analysis
  
  const random = Math.random()
  let violation = false
  let violationType = null
  let riskScore = 0
  let message = null

  // Simulate different types of violations
  if (random < 0.1) { // 10% chance of no face
    violation = true
    violationType = 'no_face'
    riskScore = 80
    message = 'No face detected in camera feed'
  } else if (random < 0.15) { // 5% chance of multiple faces
    violation = true
    violationType = 'multiple_faces'
    riskScore = 90
    message = 'Multiple faces detected in camera feed'
  } else if (random < 0.2) { // 5% chance of looking away
    violation = true
    violationType = 'looking_away'
    riskScore = 60
    message = 'Student appears to be looking away from screen'
  } else if (random < 0.25) { // 5% chance of talking
    violation = true
    violationType = 'talking'
    riskScore = 50
    message = 'Talking detected during exam'
  }

  return {
    violation,
    violationType,
    riskScore,
    message,
    faceDetected: violationType !== 'no_face',
    multipleFaces: violationType === 'multiple_faces',
    lookingAway: violationType === 'looking_away',
    timestamp: timestamp || Date.now()
  }
}

// Error handling
app.use((err, req, res, next) => {
  console.error('AI Service Error:', err)
  res.status(500).json({
    success: false,
    message: 'Internal server error',
    error: err.message
  })
})

// 404 handler
app.use('*', (req, res) => {
  console.log('404 - Route not found:', req.path)
  res.status(404).json({
    success: false,
    message: 'Route not found'
  })
})

// Start server
app.listen(PORT, () => {
  console.log(`🤖 AI Proctoring Service running on port ${PORT}`)
  console.log(`📊 Metrics available at http://localhost:${PORT}/metrics`)
  console.log(`❤️ Health check at http://localhost:${PORT}/health`)
  
  // Initialize metrics
  collectDefaultMetrics({ register })
})

// Graceful shutdown
process.on('SIGTERM', () => {
  console.log('SIGTERM received, shutting down gracefully')
  process.exit(0)
})

process.on('SIGINT', () => {
  console.log('SIGINT received, shutting down gracefully')
  process.exit(0)
})

module.exports = app
