apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-exam-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bayarmaa01/secure-exam-platform.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: exam-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
