apiVersion: v1
kind: Service
metadata:
  name: ai-proctoring
  namespace: exam-platform
spec:
  type: NodePort
  selector:
    app: ai-proctoring
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30012
  sessionAffinity: None
