apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: exam-platform
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30011
  sessionAffinity: None
