apiVersion: v1
kind: Secret
metadata:
  name: exam-platform-secret
  namespace: exam-platform
type: Opaque
stringData:
  DB_USER: exam_user
  DB_PASSWORD: exam_pass
  JWT_SECRET: "change-me-in-production-use-k8s-secrets"
  JWT_REFRESH_SECRET: "change-refresh-in-production-use-k8s-secrets"
