apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eduai
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bayarmaa01/secure-exam-platform.git
    path: eduai-k8s
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: eduai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
