frontend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-frontend
    tag: 4c86dfdd549bbc6c268e619fb514ac277d7392aa
  resources:
    limits:
      cpu: 500m
      memory: 256Mi

backend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-backend
    tag: 4c86dfdd549bbc6c268e619fb514ac277d7392aa
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi

aiProctoring:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-ai-proctoring
    tag: 4c86dfdd549bbc6c268e619fb514ac277d7392aa
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

postgres:
  enabled: true

redis:
  enabled: true

ingress:
  enabled: true
  host: exam-platform.local
