frontend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-frontend
    tag: 09c258093076bc5d8cbbdee142ef6c5070b6f2cb
  resources:
    limits:
      cpu: 500m
      memory: 256Mi

backend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-backend
    tag: 09c258093076bc5d8cbbdee142ef6c5070b6f2cb
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi

aiProctoring:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-ai-proctoring
    tag: 09c258093076bc5d8cbbdee142ef6c5070b6f2cb
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

postgres:
  enabled: true

redis:
  enabled: true

ingress:
  enabled: true
  host: exam-platform.local
