frontend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-frontend
    tag: bb247c75b4555c748801a2319fb8e69e8299aff4
  resources:
    limits:
      cpu: 500m
      memory: 256Mi

backend:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-backend
    tag: bb247c75b4555c748801a2319fb8e69e8299aff4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi

aiProctoring:
  replicaCount: 2
  image:
    repository: bayarmaa/exam-ai-proctoring
    tag: bb247c75b4555c748801a2319fb8e69e8299aff4
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

postgres:
  enabled: true

redis:
  enabled: true

ingress:
  enabled: true
  host: exam-platform.local
